name: Dependency Updates

on:
  schedule:
    # Check for dependency updates weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Update npm dependencies
        run: |
          cd contracts
          npm update
          npm audit fix --force || true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'chore: automated dependency updates'
          body: |
            This PR contains automated dependency updates.
            
            Please review the changes carefully and ensure all tests pass before merging.
            
            ---
            *This PR was created automatically by the dependency update workflow.*
          branch: automated/dependency-updates
          delete-branch: true
          base: main