name: Frontend CI

on:
  push:
    branches: [ main, develop ]
    paths: [ 'frontend/**' ]
  pull_request:
    branches: [ main, develop ]
    paths: [ 'frontend/**' ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Lint frontend
      run: npm run lint
      
    - name: Format check
      run: npm run format:check
    
    - name: Type check
      run: npm run type-check
    
    - name: Build frontend
      run: npm run build
    
    - name: Run tests
      run: npm test
      continue-on-error: true